service: apollo-lambda
provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
functions:
  graphql:
    handler: index.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true 